### ISSUE TITLE
Additional GitHub Materials/Resources

### ISSUE THREAD

**Issue by d-wasserman** [WFRCAnalytics/Resources#1]
Hey WFRC, 

I noticed some GitHub resources mentioned here, and there was a recent GitHub for Planners that might be useful to include on this page. 
https://www.youtube.com/watch?v=gVa4d728T0k

**Comment by bhereth** [comment]
Just noticing this issue. Thanks for sharing!!

**Comment by bhereth** [comment]
@d-wasserman, how can we get involved in stuff like this in the future?

**Comment by d-wasserman** [comment]
If there are members of the APA Technology Division (which I am not sure you actually need to be an APA Member), we are always looking for help putting together webinars on technical topics. Want me to raise this with other board members?

**Comment by d-wasserman** [comment]
We also have a repo we are sure your group could contribute to. 
https://github.com/APA-Technology-Division/urban-and-regional-planning-resources
